### ISSUE TITLE
shouldnt punish space after function

### ISSUE THREAD

**Issue by goyalyashpal** [cs50/style50#101]
### Summary
style50 shouldnt punish the space used between function and the bracket for arguments

### Details:
+ I am open to knowing what the experienced people think about it. But in my humble opinion:
+ The space between function name and `()` helps a lot when there are lots of arguments, or argument immediately has lots of symbols 
+ It is suggested for standard functions like `while ()`, `if ()`, `for ()` etc.
+ .... even in the cs50 styling guide as well:  https://cs50.readthedocs.io/style/c/#conditions 
![image](https://user-images.githubusercontent.com/19423063/144716626-7253a14e-ae50-4b55-b256-25cdbfed8ed2.png)
+ I get that style50 should not suggest/enforce spaces, but it should not punish them either.

### Further Screenshots:
+ Small image
![image](https://user-images.githubusercontent.com/19423063/144716652-ba50fb00-90df-4a42-96b7-f2de45732c0a.png)
+ Large 
    + `/!\` spoiler alert `/!\` : can contain solution code
    + shown in thin rectangle is the space used with standard functions
    + [image](https://user-images.githubusercontent.com/19423063/144716728-058a141b-4c98-44c0-a5a9-2aae28fb9e09.png)
 
### Environment:
+ `style50 --version` : 2.7.5  
+ ide `c9 --version` : 3.1.3534 ( https://ide.cs50.io )

------
duplicate 🔍 :  [space after function](https://github.com/cs50/style50/issues?q=is%3Aissue+space+after+function)

**Comment by dmalan** [comment]
Most style guides do not prescribe a space between a function's name and opening parentheses, I'm afraid, CS50's among them!

**Comment by goyalyashpal** [comment]
> do not prescribe a space between a function's name and opening parentheses

for functions other than `if`, `for`, `while` ; right?

**Comment by goyalyashpal** [comment]
**update:** 
i agree it's better to not have space b/w function name & opening parenthesis. there're some whitespace-sensitive languages like julia which do not allow this kind of space and treat it as syntax error. 

`syntax: space before "(" not allowed in "println (" at ...`

and so, i have just settled on space inside the parenthesis for my own style. so: `function( "string", argument2 )`
