### ISSUE TITLE
Ubuntu (20.04) repo not responding

### ISSUE THREAD

**Issue by joao-gabriel-gois** [cs50/style50#104]
According to [docs](https://cs50.readthedocs.io/style50/#installation), in order to install `style50` you need first add the repository `ppa:cs50/ppa`.

But when I perform `sudo apt-get update` just after add it, it fails to update:

```
Err:16 http://ppa.launchpad.net/cs50/ppa/ubuntu focal Release
  404  Not Found [IP: 2001:67c:1560:8008::19 80]
(...)
E: The repository 'http://ppa.launchpad.net/cs50/ppa/ubuntu focal Release' does not have a Release file.
```

Any new repo name that docs are not following yet?

__Thanks in advance__ (:

**Comment by rongxin-liu** [comment]
Could you please try installing `style50` by running `pip3 install style50`?

**Comment by dmalan** [comment]
And you can skip the `add-apt-repository ppa:cs50/ppa` step, just run `sudo apt install astyle`!
