### ISSUE TITLE
outdated on pypi ?

### ISSUE THREAD

**Issue by goyalyashpal** [cs50/style50#109]
- the [style50 files on pypi][pypi] are still said to be from 2021 july 17
- whereas the [commit history here](https://github.com/cs50/style50/commits/main) shows many more commits after that

https://pypi.org/project/style50/#files

[pypi]: https://pypi.org/project/style50/#files

<img src="https://user-images.githubusercontent.com/19423063/229160191-0523ea2b-7802-48e1-b4dd-4f26722ff266.png" width=650px/>

**Comment by rongxin-liu** [comment]
These commits were not related to style50.
