### ISSUE TITLE
typedef struct - type name in own line marked as error

### ISSUE THREAD

**Issue by pullant** [cs50/style50#113]
In plurality.c this code is provided by CS50 following CS50 guidelines for C:

```c
typedef struct
{
    string name;
    int votes;
}
candidate;
```

But style50 marks it as bad style and sugest:

```c
typedef struct
{
    string name;
    int votes;
} candidate;
```

**Comment by rongxin-liu** [comment]
This is the convention adopted by clang-format, the underlying formatter for C/C++ in style50.
It is not necessarily that your code is "bad". But please follow what style50 suggests for now!
