### ISSUE TITLE
quotes issue

### ISSUE THREAD

**Issue by Shikots** [cs50/style50#116]
Using both double quotes here`print(f"{row["name"]}")`prevented style50 from running, giving the message "Can't check your style just yet! Try running your code, fix any errors, then check its style again!".  This is in python.

My code ran correctly and passed check50. Switching the outer quotes to singles let style50 run and allowed my submission to be graded. 
Don't know enough to say, but I'd guess the issue is related to being within brackets/curly-braces/parentheses and having inner and outer quotes within them. Maybe something else in there too, haven't looked at style50's code to find out.

**Comment by rongxin-liu** [comment]
Thanks for reporting!

We are waiting for the `Black` formatter to be updated:
https://github.com/psf/black/pull/3822

**Comment by JelleZijlstra** [comment]
I learned to program in CS50 some years ago, and now I help maintain Black, the open-source formatter that style50 uses for Python code :)

For context, the syntax you're using was only added to Python very recently, and we haven't had a chance to add support for it in Black just yet—hopefully soon!

**Comment by rongxin-liu** [comment]
> I learned to program in CS50 some years ago, and now I help maintain Black, the open-source formatter that style50 uses for Python code :)
> 
> For context, the syntax you're using was only added to Python very recently, and we haven't had a chance to add support for it in Black just yet—hopefully soon!

Thanks!

I think most of our students ran into issues where they would use double-quote in an `f-string` that would expectedly crash `black`.

For example, this code snippet is valid in `Python 3.12`:

```python
apple = "apple"
print(f"{"an " + apple}")
```

But running `black` we would get this error:

```
$ black hello.py 
error: cannot format hello.py: Cannot parse: 2:10: print(f"{"an " + apple}")

Oh no! 💥 💔 💥
1 file failed to reformat.
```

If we use the python black module, it would crash:

```
                  ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/style50/languages.py", line 71, in style
    return black.format_str(code, mode=black.FileMode())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/black/__init__.py", line 1156, in format_str
    dst_contents = _format_str_once(src_contents, mode=mode, lines=lines)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/black/__init__.py", line 1170, in _format_str_once
    src_node = lib2to3_parse(src_contents.lstrip(), mode.target_versions)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/black/parsing.py", line 89, in lib2to3_parse
    raise exc from None
black.parsing.InvalidInput: Cannot parse: 2:10: print(f"{"an " + apple}")
```
