### ISSUE TITLE
Why are single quotes always being considered an error?

### ISSUE THREAD

**Issue by RhFortuna** [cs50/style50#117]
![file](https://github.com/cs50/style50/assets/66008341/275057c2-81d0-4b29-9671-77d4e7df4c2d)

style50 2.9.0

**Comment by rongxin-liu** [comment]
Can you please send your full code to sysadmins@cs50.harvard.edu?

**Comment by RhFortuna** [comment]
Sure, but it's not my code, just an example.

A simpler example:

```
l = ['consider', 'dream', 'forget', 'imagine', 'ponder', 'remember', 'memorize', 'learn',
     'think', 'worry', 'fear', 'doubt', 'condemn', 'analyze', 'review', 'dread',
     'fantasize', 'appreciate', 'evaluate', 'ask', 'go', 'eat', 'walk', 'run', 'swim',
     'bend', 'climb', 'kick', 'hang', 'open', 'pull', 'yell', 'leap', 'unlock', 'lock',
     'seal', 'kill', 'stop', 'steal', 'save', 'recue', 'arrest', 'destroy', 'escape',
     'deliver', 'summon', 'capture', 'trick', 'collect', 'infiltrate', 'restore', 'heal',
     'convert', 'preserve', 'reveal', 'locate', 'control', 'wake', 'dance', 'build']

l.sort()

print(l)

s = set(l)

print(len(l))

print(len(s))
```

![style50](https://github.com/cs50/style50/assets/66008341/5a94c2c9-99a0-4bba-adf3-56e9ebedf97f)

**Comment by RhFortuna** [comment]
Using a better organized list:

![style50](https://github.com/cs50/style50/assets/66008341/0ca31430-2714-4d6e-91f2-26fe2d60e95e)

**Comment by dmalan** [comment]
Stylistically, the formatter that `style50` uses, Black, prescribes double quotes!

https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html#strings
