### ISSUE TITLE
confusingly (but correctly) adds red \n

### ISSUE THREAD

**Issue by dmalan** [cs50/style50#12]
**input**

```
#include <stdio.h>

int main(void)
    {
printf("hello, world\n");
    }
```

**output**

<img width="296" alt="screen shot 2017-08-11 at 4 34 01 pm" src="https://user-images.githubusercontent.com/788678/29230907-f9f6c0ca-7eb2-11e7-81c9-eb1185f93b7d.png">

**Comment by dmalan** [comment]
Oh I see what happened here. Interesting, though non-obvious. Guessing it's the underlying algorithm that decided to advise removing `{\n` and re-adding `{\n` as opposed to unindenting the `{` and indenting the `printf`? Do we've any control over those kinds of mutation decisions?

**Comment by cmlsharp** [comment]
We have no control over this. I just format what is given to me by Python's `difflib`
