### ISSUE TITLE
Get ImportError when running style50 on WSL ubuntu 20.04

### ISSUE THREAD

**Issue by Jesseekoh** [cs50/style50#123]
I recently installed Style50 on my WSL setup and I keep getting : ImportError: cannot import name 'files' from 'importlib.resources' (/usr/lib/python3.8/importlib/resources.py).
I also experience the same thing running other tools like check50 and submit50.
![Screenshot 2024-03-25 085433](https://github.com/cs50/style50/assets/35234307/dc66a90f-ff61-4d58-998c-503f4d89dc1d)

**Comment by rongxin-liu** [comment]
Please ensure you are running Python 3.12 in your environment. Or use https://cs50.dev instead.
