### ISSUE TITLE
change MODE to mode

### ISSUE THREAD

**Issue by dmalan** [cs50/style50#27]
Seems inconsistent to capitalize just that one?

**Comment by cmlsharp** [comment]
Metavars are capitalized by convention e.g. from `ls --help`

```
Usage: ls [OPTION]... [FILE]...
```
or
```
       --block-size=SIZE      scale sizes by SIZE before printing them; e.g.,
                               '--block-size=M' prints sizes in units of
                               1,048,576 bytes; see SIZE format below

```

Might it be better to make it consistent by capitalizing "file" e.g. `usage: style50 [-h] [-o MODE] [-v] [-V] FILE [FILE ...]`?
