### ISSUE TITLE
change blue :::::::::::::: to just white text

### ISSUE THREAD

**Issue by dmalan** [cs50/style50#28]
Just unnecessary color, darkens output too.

**Comment by cmlsharp** [comment]
The color makes it easy to quickly differentiate between files when running `style50` on lots of files (which I found very useful when testing it). White text, even with the many ':' was often easily lost. Additionally, I tried to enforce that white text was unambiguously only ever student code.

I would be strongly in favor of keeping the header colored in some way, though of course I'll change it if the above reasoning isn't convincing. If the brightness is the problem, I can use a brighter color.
