### ISSUE TITLE
unnecessarily suggesting that students break short conditions across lines

### ISSUE THREAD

**Issue by dmalan** [cs50/style50#29]
<img width="225" alt="screen shot 2017-09-09 at 3 29 34 pm" src="https://user-images.githubusercontent.com/788678/30243283-49a60a22-9574-11e7-869d-51574cbebcac.png">

**Comment by brianyu28** [comment]
I wonder if this is just `astyle`'s way of enforcing the maximum 100 character per line limit?

https://github.com/cs50/style50/blob/develop/style50/languages.py#L18

**Comment by dmalan** [comment]
Indeed, seems screenshot wasn't consistent with what was in code editor. Disregard, @crossroads1112!
