### ISSUE TITLE
possible additional (subtler) errors/warnings

### ISSUE THREAD

**Issue by tobiasbueschel** [cs50/style50#3]
### Further improvements

- (1) multiple lines of declarations that should be 1
- (2) parenthesized expression that doesnt need to be (like only the topmost level one, to be safe)
- (3) any guidelines on how to space things out (like where to put blank lines?)
- (4) new line between last include and next line

```c
// possible additional (subtler) errors/warnings #3
#include <stdio.h>
#include <stdio.h>
int main(void)
{
    // (1) multiple lines of declarations that should be 1
    int x = 1;
    int y = 0;
    int z = 0;

    // (2) parenthesized expression that doesnt need to be (like only the topmost level one, to be safe)
    if (x == (0))
    {
        printf("x is zero\n");
    }

    // (3) any guidelines on how to space things out (like where to put blank lines?)
    // e.g should below cause style50 to recommend adding a new line between the variable declarations
    // and the if condition?
    int quarters, dimes = 0, nickels = 0, pennies;
    if (x > 0)
    {
        printf("x is positive\n");
    }

    // (4) new line between last include and next line
    // see above, also shall we check for duplicate includes?
}
```

// style50 output
// 😯  9:8  "z" is rather short for an identifier's name. Be sure it's descriptive.
// 😯  11  Line is 104 characters long, longer than max length of 80.
// 😯  17  Line is 85 characters long, longer than max length of 80.
// 😯  18  Line is 102 characters long, longer than max length of 80.
// 😰  20  Initialized some but not all variables.

**Comment by tobiasbueschel** [comment]
@dmalan & @dlloyd09, please let me know what you think about above: 1, 2, 3, and 4.

**Comment by dlloyd09** [comment]
(1) I don't think we need to warn or error about.
(2) If it can be done accurately with respect to operator precedence rules, making 100% certain that removing the parentheses will not affect the students' logic, probably a nice thing to warn (but not error) about.
(3) I don't think we have any consistent guidelines in style50 on this. I would probably put a space there, but others might not. @dmalan might have a definitive suggestion here.
(4) Ditto.

**Comment by tobiasbueschel** [comment]
Regarding (4), the ANTLR C grammar only supports preprocessors to a [very limited extend](http://stackoverflow.com/questions/25010496/why-is-there-no-viable-alternative-for-include-statement-in-antlr-4-with-c-gram), hence, we could add additional parsing rules to generate preprocessor directive tokens and append the latter to the AST.

However, rather than tokenizing preprocessor directives, I found an arguably more straightforward solution, implemented here: https://github.com/cs50/style50/commit/a5d055ab001e925f5ea804893cf73e90c8e417e7

As for (1) & (3), I had a chat with David and he suggested leaving them and putting (2) on hold.

Therefore, I shall close the issue for the time being.
