### ISSUE TITLE
remove \n from colored output?

### ISSUE THREAD

**Issue by dmalan** [cs50/style50#30]
In office hours tonight, I notice a student had added literal `\n`'s to their file, a misinterpretation of `style50`'s output. Should we perhaps eliminate our explicit mention of `\n` after all, and leave it to the user to infer that seeing code on a separate line implies the addition of `\n`, even though we'd no longer be highlighting it explicitly? We had a question on CS50 Discourse earlier this week too. So I worry our highlighted `\n` might be confusing more than helping?

<img width="283" alt="screen shot 2017-09-14 at 1 52 06 am" src="https://user-images.githubusercontent.com/788678/30414046-a117c8bc-98ef-11e7-867c-22e397413f75.png">

CC @brianyu28 @kzidane

**Comment by brianyu28** [comment]
I've actually seen this confusion a couple times at office hours myself as well (in addition to the Discourse question). I think removing the `\n` makes sense too.

**Comment by cmlsharp** [comment]
What should be put there instead? If nothing at all, it might also be confusing if `style50` outputs a long file with the only changes being a couple added newlines. It'd be almost impossible to spot the changes it made.

As an alternative, we could go back to the ↪ character, but it doesn't look great in the terminal

Do we still put a red `\t` when removing tabs?

**Comment by dmalan** [comment]
Per chat, going with an end-of-output legend explaining what a green/red `\n` and a red `\t` mean!
