### ISSUE TITLE
keep green \n at ends of earliest lines?

### ISSUE THREAD

**Issue by dmalan** [cs50/style50#39]
Sample input:

```python
# Abstraction with parameterization

def main():
    cough(3)

def cough(n):
    """Cough some number of times"""
    for i in range(n):
        print("cough")

if __name__ == "__main__":
    main()
```

Output of `style50`:

<img width="340" alt="screen shot 2017-10-11 at 9 27 36 pm" src="https://user-images.githubusercontent.com/788678/31479313-34a26d4e-aecb-11e7-90bf-ae7062bdf389.png">

Feasible to process the diff such that those first two `\n` get "pulled up" to be at the ends of the preceding non-blank lines, such that the first appears as `...parameterization\n` and the second appears as `cough(3)\n`?

Feels more clear that way as to where student can/should hit Enter?

**Comment by cmlsharp** [comment]
This would require some very nontrivial changes to how the diff is processed. All of the diff functions return an iterator over the lines of the diff. Implementing this feature would require arbitrary lookahead, which while doable, would likely increase the complexity a fair bit.

I'm also not sure that this use case warrants such an increase. Telling students to hit Enter just before `def cough(n):` seems just as clear to me as telling them to hit enter after `cough(3)`
