### ISSUE TITLE
if no file extension, infer language from shebang, if any

### ISSUE THREAD

**Issue by dmalan** [cs50/style50#40]

**Comment by cmlsharp** [comment]
Maybe better to use `libmagic`, (what the `file` command uses)? It seems to be a bit more robust (and doesn't rely on file extension at all).

**Comment by dmalan** [comment]
Aok! Any chance you can tackle this one today, @crossroads1112, in anticipation of pset6?

**Comment by cmlsharp** [comment]
Sorry for the delay, but it is now implemented
