### ISSUE TITLE
shouldn't complain when file is missing a trailing \n

### ISSUE THREAD

**Issue by dmalan** [cs50/style50#46]
<img width="505" alt="screen shot 2017-10-28 at 11 53 54 pm" src="https://user-images.githubusercontent.com/788678/32140540-55e6868e-bc3b-11e7-8357-f42f6292de6b.png">

CC @brianyu28 @kzidane

**Comment by cmlsharp** [comment]
Trailing newline is specified in PEP8 and `autopep8` doesn't directly allow this check to be disabled, but can definitely be done.
