### ISSUE TITLE
require autopep8 1.3.3?

### ISSUE THREAD

**Issue by dmalan** [cs50/style50#47]
Else with 1.3.2, as is currently installed on IDE:

<img width="240" alt="screen_shot_2017-10-28_at_11 51 45_pm_480" src="https://user-images.githubusercontent.com/788678/32140562-0b7b6e56-bc3c-11e7-9679-e406e672f96a.png">

But with 1.3.3, as is currently installed in `cs50/ecs`:

![style50_360](https://user-images.githubusercontent.com/788678/32140563-1378b262-bc3c-11e7-8264-13472c7bb4dd.png)

CC @brianyu28 @kzidane @glennholloway @curiouskiwi

**Comment by cmlsharp** [comment]
@49
