### ISSUE TITLE
Run style50 only on student code

### ISSUE THREAD

**Issue by brianyu28** [cs50/style50#55]
Use case is for CS50 Finance, where we only want to grade percentage of correct lines in `application.py` but not `helpers.py`. Right now the ECS script just grades the entire directory, and has no way of knowing that `application.py` should be graded but `helpers.py` shouldn't.

Think we might be able to let `style50` (when a particular command-line flag is used) interpret the `exclude` files in `cs50/checks` to know which files to score?

cc @dmalan

**Comment by cmlsharp** [comment]
Where's the best place for it to look for the exclude file? Or should check50 just pass the location via command line option?

**Comment by dmalan** [comment]
Discussing tomorrow afternoon; will loop back!
