### ISSUE TITLE
Add test for correct declaration of main

### ISSUE THREAD

**Issue by curiouskiwi** [cs50/style50#72]
The Style Guide outlines the choices for declaring main:

    int main (void)
    int main (int argc, string argv[])
    int main (int argc, char *argv[])
    int main (int argc, char **argv)

Style50 does not currently check for one of those and says "Looks good" for

    int main()
    main()
    int main (int a, char *b[])

as examples.  (`main()` will be caught by make)

**Comment by cmlsharp** [comment]
`astyle` doesn't have a check for this, nor do any of the other C style tools I'm aware of (ClangFormat etc.) so my hands might be tied. I also think we've internally settled on "style" being "whitespace", and changing function declarations is a bit outside that scope (in a similar respect, style50 does not check variable names).
