### ISSUE TITLE
Error using style 50 on a macbook

### ISSUE THREAD

**Issue by RobertFloor** [cs50/style50#92]
I am trying to run the style50 program locally on my macbook. I would like to evaluate my answers before submitting them. I installed it according to the instructions given heren: https://cs50.readthedocs.io/style50/ (sudo pip3 install style50). I also installed astyle (the Mac version). This all worked well. When I run style50 I get the following error. Thank you in advance for helping me!
````
robertfloor$ style50 hello.c

Traceback (most recent call last):
  File "/usr/local/bin/style50", line 11, in <module>
    load_entry_point('style50==2.7.3', 'console_scripts', 'style50')()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2793, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2411, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2417, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/site-packages/style50/__init__.py", line 20, in <module>
    from ._api import Style50, StyleCheck, Error
  File "/usr/local/lib/python2.7/site-packages/style50/_api.py", line 97
    termcolor.cprint(f"To see results in your browser go to file://{html_file.name}", "white", attrs=["bold"])
                                                                                   ^
SyntaxError: invalid syntax
````

**Comment by RobertFloor** [comment]
The problem occurs because python2 is running a python3 syntax. 
Somehow the installation is mixed between python 2 and 3. The instructions are different on different pages whether to use pip or pip3. The pip3 version can be install but gives the following error:
```

$ sudo pip3 install style50

$ style50
-bash: /usr/local/bin/style50: No such file or directory

```

**Comment by RobertFloor** [comment]
So I fixed the problem. The issues seems to be not to use pip but use pip3 to install style50. I first uninstall it using pip and installed it with pip3. The documentation should be updated. I then encountered another error when the program could not find libmagic. I solved this via this comment (https://github.com/Yelp/elastalert/issues/1927)

This solved this issue for me:

```
pip uninstall python-magic
pip install python-magic-bin==0.4.14
```

**Comment by whithedel** [comment]
@RobertFloor thank you so much i spent 3 days trying to figure this out. what a releif.

**Comment by whithedel** [comment]
@RobertFloor thank you so much i spent 3 days trying to figure this out. what a releif.
