### ISSUE TITLE
Style50 unhappy with just about all indentation

### ISSUE THREAD

**Issue by Anonymous-Humanoid** [cs50/style50#98]
The following images have been cropped so as to not give away any sort of idea regarding a solution to pset1's "credit" problem. However, the image on the left does show how much indenting I used for this particular problem, and the image on the right shows the output from running `style50 credit.c`, see below:
![Screenshot (143)](https://user-images.githubusercontent.com/68610963/88836310-7cfcb780-d1a4-11ea-8546-c748f5a2e938.png) ![Screenshot (144)](https://user-images.githubusercontent.com/68610963/88837911-c77f3380-d1a6-11ea-8e77-6f93afbe3db5.png)
From the above images, we can see that style50 appears to be inputting twice as many indentations as there actually are before marking them up. Earlier, it even decided that the indentation was fine up until line 12. Not sure why it worked only then. Finally, I don't have an image handy to support this final statement, but style50 seems satisfied only when no indentation exists anywhere in the program.
I think I can speak for the students of CS50x when I say we'd appreciate this being fixed within a reasonable time frame.

Thanks, CS50 Team!

**EDIT**: Now this is occurring within only the Main function, and only in this credit.c program of mine.
Keep up the good work!

**Comment by Anonymous-Humanoid** [comment]
Never mind.
This problem was quite easily fixed by manually replacing each and every instance of a tab with four spaces.

Still, keep up the good work, CS50 Team!

**Comment by goyalyashpal** [comment]
hi, refer to this document:
https://cs50.readthedocs.io/style/c/#indentation

> If you use your keyboard’s Tab key to do so, be sure that your text editor’s configured to convert tabs (\t) to four spaces...
